export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_NAVBAR = 'TOGGLE_NAVBAR'

export const TOGGLE_LOGIN = 'TOGGLE_LOGIN'

export const TOGGLE_SIGNUP = 'TOGGLE_SIGNUP'

export const TOGGLE_SCROLL_DIRECT = 'TOGGLE_SCROLL_DIRECT'

export const LANGUAGE = 'LANGUAGE'

export const MENU_ITEM = 'MENU_ITEM'

export const SITE_NAME = 'SITE_NAME'

export const SITE_DOMAIN = 'SITE_DOMAIN'

export const USER_INFO = 'USER_INFO'

export const USER_LOGOUT = 'USER_LOGOUT'

export const ITEMS = 'ITEMS'

export const ITEMS_APPEND = 'ITEMS_APPEND'

export const ITEM_NOWPAGE = 'ITEM_NOWPAGE'

export const ITEM_SEARCH_RESULTS = 'ITEM_SEARCH_RESULTS'

export const ITEM_SEARCH_MODE = 'ITEM_SEARCH_MODE'

export const ITEM_SEARCH_RAW_TEXT = 'ITEM_SEARCH_RAW_TEXT'

export const ITEM_SEARCH_ORDERBY = 'ITEM_SEARCH_ORDERBY'

export const ITEM_SEARCH_RESULT_MODE = 'ITEM_SEARCH_RESULT_MODE'

export const PROPERTIES = 'PROPERTIES'
